version: "3.8"
services:
  #作成したいサービス（コンテナ）定義
  db:
    image: mysql
    # Mac(M1)を使用している場合、platformに関するエラーが発生する可能性がある。エラー発生してから追加するのも良し。
    platform: linux/x86_64
    env_file: development.env
  web:
    # 作成済みのDockerfileを元にコンテナを作成
    build:
      # Dockerfileでファイルの読み込み先を指定
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/blog
      - gem_data:/usr/local/bundle
    ports:
      - "3000:3000"
    # コンテナの立ち上げ順と依存関係を指定。dbコンテナが立ち上がってからwebコンテナが立ち上がるようにする。
    depends_on:
      - db
    env_file: development.env
    # stdin_open, ttyは`pry-byebug`を使用するために記述
    stdin_open: true
    tty: true
    # command: bundle exec rails server -b 0.0.0.0 重複エラー　Railsサーバー起動するが、cmd上でやるのでいい。
volumes:
  dbvolume:
  gem_data:
